"""
Phase 4: email verification token generation.

Isolated from auth_routes.py / models.py for the same reason security.py
is: focused, independent tests, and a single place that must never log a
raw token.

Why SHA-256 here, not Argon2id (used for passwords in security.py):
Argon2 is deliberately slow and memory-hard to defend against offline
brute-forcing of LOW-ENTROPY, human-chosen secrets like passwords. A
verification token generated by secrets.token_urlsafe(32) has 256 bits of
real entropy - it is not guessable, so a fast, deterministic hash is both
sufficient and the right tool: it lets the verification endpoint look the
token up by an indexed equality query (`WHERE token_hash = ?`) instead of
loading every unexpired token and comparing each one, which is both
standard practice (GitHub, Django, etc. do the same) and clearly documents
that fast hashing here is not a mistake.
"""

import hashlib
import secrets
from datetime import datetime, timedelta, timezone

TOKEN_BYTES = 32  # 256 bits of entropy - not guessable/brute-forceable
TOKEN_EXPIRY_HOURS = 24  # documented expiration window for Phase 4


def generate_verification_token():
    """Returns (raw_token, token_hash, expires_at).

    raw_token: only ever placed in the verification email/link - never
        written to the database or logged anywhere.
    token_hash: what actually gets stored (see EmailVerificationToken).
    expires_at: timezone-aware UTC datetime, TOKEN_EXPIRY_HOURS from now.
    """
    raw_token = secrets.token_urlsafe(TOKEN_BYTES)
    token_hash = hash_token(raw_token)
    expires_at = datetime.now(timezone.utc) + timedelta(hours=TOKEN_EXPIRY_HOURS)
    return raw_token, token_hash, expires_at


def hash_token(raw_token):
    return hashlib.sha256(raw_token.encode("utf-8")).hexdigest()


def ensure_aware_utc(value):
    """Normalizes a datetime that may have come back timezone-NAIVE from
    a database backend into a timezone-AWARE UTC datetime.

    Root cause this fixes: SQLite has no native timezone-aware storage
    type. Even with SQLAlchemy's `DateTime(timezone=True)` (used
    throughout models.py and the migrations - correct for PostgreSQL,
    which DOES store the offset), real SQLAlchemy's SQLite dialect
    returns naive datetimes on read. Comparing that naive value against
    `datetime.now(timezone.utc)` (aware) raises
    `TypeError: can't compare offset-naive and offset-aware datetimes`.

    Every datetime this application ever writes is already UTC (see
    generate_verification_token() above and models._utcnow()) - so a
    naive value read back always means "naive but actually UTC", never an
    ambiguous local time. This function normalizes on the way IN to a
    comparison (attaching UTC to a naive value) rather than stripping
    tzinfo from `now` on the way OUT, which would silently discard
    precision instead of fixing the actual representation mismatch, and
    would violate the "don't weaken expiration checks" requirement by
    making both sides less precise instead of both sides correct.

    Safe to call on an already-aware datetime (converts it to UTC, a
    no-op if it's already UTC) or on None (returns None unchanged).
    """
    if value is None:
        return None
    if value.tzinfo is None:
        return value.replace(tzinfo=timezone.utc)
    return value.astimezone(timezone.utc)
